### ISSUE TITLE
Auto Relist Price Change.

### ISSUE THREAD

**Issue by debugger48** [Mardaneus86/futwebapp-tampermonkey#102]
Today I updated from the separate scripts version to the unified version.
I enabled `Relist expired auctions automatically` and `Relist at BIN price` (with default options)

I had a TOTGS Kimmich listed up for `174,500` (his lowest bin was ~165k) and I came back a few hours later to find that he sold for a BIN of **`75,500`**.
How could this have happened? What exactly does 'Relist at BIN price do' ? 
Did it do a price check and at that moment there happened to be another card for that price?

### Metadata:
- **Script version:** 0.2.3
- **Browser:** Chrome
- **OS:**  MacOS 10.13.2

**Comment by Mardaneus86** [comment]
If you enable the option to relist at BIN price, it looks up the minimum BIN on the market first, and then relists at the percentages that you set in the settings. If you disable the `Relist at BIN price` option, it relists at the previous list price without looking at the market.

There might be a bug in the min BIN price checker for these more special cards (can't debug that easily since I don't have any). Since the transfer market is searchable for "Special" cards only, I can imagine an issue there. Perhaps another option is to exclude special cards from the min BIN, or to use Futbin prices for those.

I am aware that documentation is lacking at this moment.

Thanks for reporting, and sorry for any inconvenience that this caused 😒.

**Comment by Feigenstaub** [comment]
Funny (or even not) but I came here to ask for that option aswell what it really does. Coz I have many 83 rated cards and I list them at 4k, usual price is 2,8k -3k, and I thought the relist at BIN price (it's not called lowest bin) relist the cards at a % as they were listed before. 
e.g. I listed at 4k before and the script list them at 3,9k, then 3,8k, then 3,7k ...
Thought the option does that and I am glad that it only worked only for 3 cards for me.

Relist at lowest bin (does it take the real lowest or the one which can be calculated through the script like with the 5 lowest bins) sounds like an interesting option too, but... what about relist at like 99% of the last listed price like my example?
is that possible?

cheers

**Comment by Mardaneus86** [comment]
I've never looked at it that way, but if there is this much confusion about it I'll have to clarify in the UI. Thanks for the response.

It does look at the average/median of the lowest 5 BIN's right now.

Relisting at 99% of last list price would certainly be possible, but that would require a minimum of 1 price tick below the previous list price to work correctly. Otherwise, for example, 99% of 500 would become 495, which would round of to 500 again.

**Comment by Feigenstaub** [comment]
Okay sure, 99% on low prices would result in the same price but there could be a field to put in any percentage you want. Or maybe just go a number of price ticks below, idk

It would be really nice if u can add this :)

**Comment by debugger48** [comment]
Maybe another safety feature (could be an exposed setting) where if the calculated new bin price is X% of the previous value it won't list it up

**Comment by Mardaneus86** [comment]
That is actually quite a good idea. Will keep it in mind for the next release.

If anyone is up for it, please add a PR.

**Comment by Feigenstaub** [comment]
Any timeframe for the next release? last one is way back. And with which features can we plan?

**Comment by Mardaneus86** [comment]
That depends on when I find some spare time, I'm also working on other projects simultaneously. So no ETA at the moment.

Would love to see some other developers joining to help out on implementing features like this.

**Comment by Bendecks** [comment]
On a slight sidenote, but related: When relisting on  a new BIN, searching for the new BIN there should be a time delay to mimic human behavior. Atm it triggers a lot of captchas.

**Comment by Mardaneus86** [comment]
There is a 3 second delay between every action + the time it takes to search for the minimum BIN which also includes time delays. Probably it causes issues when relisting too many items separately? The RPM is probably too high in that case. I have a basic RPM limiter working in my dev branch, but that needs quite some more finetuning, which might resolve this problem in the future.

**Comment by Mardaneus86** [comment]
This feature is no longer in the FIFA 19 script, and will not be provided since I decided not to add any automation in this script.
