### ISSUE TITLE
Search Minimum BIN Setting To Automatically scan and search the whole page.

### ISSUE THREAD

**Issue by spd85** [Mardaneus86/futwebapp-tampermonkey#103]
### Expected behavior:

Can we maybe have a setting that searches the minimum BIN Setting Automatically when you open packs and also when searching page by page thru the CLUB?

### Current behavior:

Right now i have to manually click each person to see the min BIN before posting when both opening packs and looking thru my club for "gems"

### Metadata:
- **Script version:**
- **Browser:**
- **OS:**

**Comment by spd85** [comment]
Thank you for all your work btw! Love the script

**Comment by Mardaneus86** [comment]
This is certainly possible, but it would probably trigger a lot of captcha's because of the repetitive nature of these actions, especially when it is done when browsing through the club. Those captcha's in turn will result into your account being investigated with a potential ban as a result. It would also take quite some time to look up the BIN prices for every player on a page.

The feature would be viable when opening packs, because that is an action that isn't performed as often as browsing a club.

A possible workaround is to use the Futbin price feature first, to filter out the useless players. Then only search BIN prices for those players that look interesting.

As stated in other comments, I'm lacking the time right now to implement new features, so I can't give an ETA when this will be available. I'm happy to accept PR's for this.

**Comment by Mardaneus86** [comment]
I feel this would require too many requests for a limited usage, so not putting effort into this. If someone feels the urge, please add a PR.

Cleaning up the issue list for the FIFA 19 update.
