### ISSUE TITLE
How can I get the current bid?

### ISSUE THREAD

**Issue by JhonMaya** [Mardaneus86/futwebapp-tampermonkey#139]
not the initial bid but the current bid

Peace!

**Comment by Mardaneus86** [comment]
Can you elaborate a bit? Not sure what it is that you want? For discussions please use the Gitter channel!

**Comment by JhonMaya** [comment]
startingBid: prices.start, <-- this get initial bid  and
buyNowPrice: prices.buyNow, <-- this get buy now value 
I'd like to know how to pick up the current bid.
![ing](https://user-images.githubusercontent.com/4957557/47091883-26570100-d1fc-11e8-8e33-71d4235e9fc6.png)

**Comment by Mardaneus86** [comment]
"pick up the current bid"? To do what exactly?

**Comment by Mardaneus86** [comment]
Closing in favor of #121 then. 

As mentioned before I'd like to get a good overview of all possibilities first before implementing something. Every new feature will cost maintenance effort so I'd like to be careful with the stuff I add. This might become a rabbithole I don't want to get myself involved in unknowingly 😄

@JhonMaya please reopen if you meant something else, but be more clear about what you want in that case. Otherwise, discuss further in #121.
