### ISSUE TITLE
Download club info in csv/excel format

### ISSUE THREAD

**Issue by NapStudio** [Mardaneus86/futwebapp-tampermonkey#201]
READ BEFORE YOU ADD AN ISSUE: Do not request autobuyer features, because they are considered as cheating. Issues regarding autobuyers will be closed immediately.

### Expected behavior:
Download club info in csv/excel format. This options was available before, I can't find it now

### Current behavior:
This posibility got remove

### Metadata:
- **Script version:**
- **Browser:**
- **OS:**

**Comment by Mardaneus86** [comment]
Since it needs to loop over all your club pages it is a fairly dangerous action to do, you might have tens of pages of players which can result in a huge amount of requests that can get you banned if they are done too quickly. I have no idea what rate limit would be safe, that's why I removed it in FIFA 20.

**Comment by pjar** [comment]
It might be safe doing this futbin-fetcher way - have an option to gather data through manual user paginating in the webapp. At the end he clicks 'Ready' and file is generated from the cached data.
