### ISSUE TITLE
request for more than 30 items per page on transfer market

### ISSUE THREAD

**Issue by gauravbellani** [Mardaneus86/futwebapp-tampermonkey#212]
Happy new year everyone !

Is there any reason why the items per page are capped to 30 and 90 on the market and club page ? im okay with 90 on the club page, but is it possible to increase the number of items per page on the market to more than 30 ?

**Comment by gauravbellani** [comment]
Hi, is this project alive ? hasn't been an update or a response for a while now

**Comment by Mardaneus86** [comment]
Hi, the project isn't dead, but I just didn't have time and am still looking for a maintainer who can help me when I don't have time.

To answer your question, having the market page getting more than 30 items is something the normal app doesn't allow without doing more than one request. This might endanger you to getting banned, and that's the last thing I want to happen.

For the clubs page, 90 players are fetched and then 3 pages are used without additional requests (at least in FIFA 20).

So closing this issue since it isn't something for the masses.
