### ISSUE TITLE
Cache or RateLimit Futbin requests

### ISSUE THREAD

**Issue by debugger48** [Mardaneus86/futwebapp-tampermonkey#28]
If I scroll through a few pages of players in my club the futbin prices stop showing up.
I'm not seeing the requests in the network inspector but I believe futbin may be rate limiting it.
Maybe the script show also do a rate limit and/or have a local cache of prices (e.g. for 1h)

**Comment by Mardaneus86** [comment]
You won't see the network requests because they are sent through Tampermonkey, this prevents CORS failures. I haven't seen any rate limiting by Futbin as of yet. Probably the script is not picking up on the page changes correctly.

However I don't have multiple pages of players in my club so I can't test this.
