### ISSUE TITLE
[request] support writing sold item data to local file

### ISSUE THREAD

**Issue by fifa2017player** [Mardaneus86/futwebapp-tampermonkey#61]
### Expected behavior:
Similar to how one of the scripts supports exporting data of sold items to ifttt, it would be great if the script could allow just writing to a local file for people who don't want to use ifttt, or want an easily accessible local log file.

### Current behavior:
Give a detailed explanation of the current behavior.

### Metadata:
- **Script name:** 
- **Script version:**
- **Browser:**
- **OS:**

**Comment by Mardaneus86** [comment]
There’s actually no way to write directly to a file with JS because of the sandboxed environment.

You will have to use ifttt and connect to a dropbox file or something alike if you want easy local access.

It is possible to show a download dialog for files though, would that work for you?

Spinning up a local webserver is another possibility, but that isn’t something I want to offer to the main public of these scripts.

**Comment by fifa2017player** [comment]
I see, thanks for the explanation.

Yes, showing a dialog to download a file that has a record of all the cleared sales so far would be great too!

**Comment by Mardaneus86** [comment]
Fixed in [v0.2.1](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/v0.2.1).
