### ISSUE TITLE
buy players automatically

### ISSUE THREAD

**Issue by martman85** [Mardaneus86/futwebapp-tampermonkey#7]
What would be really awesome for me is if there is a way to automatically buy players. So, I would set some criteria in this script (for example: rare gold players from bundesliga < 1000) and then buy 30 players that fit the criteria.

**Comment by jhuriez** [comment]
I have found this "controllers.items.ItemDetails.prototype._onBuyNow" for buyNow, but i don't know how call this function ...

**Comment by jhuriez** [comment]
For bid 1000 on the first result, we can't just bid with this ? => 

`gNavManager.getCurrentScreenController()._controller._listController._viewmodel._collection[0]._auction.bid(1000);`

**Comment by Mardaneus86** [comment]
That's an option as well. But you would still need to determine whether you should bid or not.

I did some further research to find out if it is possible to implement. In order to search the market and get the trade IDs you could do the following:

```
var t = new transferobjects.SearchCriteria();
t.maxBuy = 3000; // or any other option you want
var o = new communication.SearchAuctionDelegate(t);
o.addListener(communication.BaseDelegate.SUCCESS, this, function marketSearch(sender, response) {
  // response.auctionInfo is an array that contains all auction data, including tradeId
});
```

This combined with the previous snippet could work for an initial version.

**Comment by Mardaneus86** [comment]
Made a UI for the proof of concept. This inherits from the `pages.Search` screen. Seems to work for BIN sniping. The rest of the app stays usable while the buyer works.

Current limitations are:
- Unable to search for rare flag (for example to search rare gold player contracts). This would require paging
- Not listing bought items instantly (requires more input fields in the search criteria area)
- Only one type of item can be searched at once
- Based on Buy Now price only (otherwise we have to keep track of trade status and implement bidding logic. This is doable but way more complex.)
- Causes Captcha verification every few hours

![autobuyer-bin-snipe-screen](https://user-images.githubusercontent.com/7780108/30909747-7dea516e-a382-11e7-95f8-188ce47913a5.jpg)

Is something like this what you had in mind?

**Comment by martman85** [comment]
That looks good. Too bad about the rare players, but there can be worked around that, by simply searching for a specific rare player.
I am missing the ability to bid. From the mockup it seems you can only buy (correct me if i'm wrong). However the ability to **bid** would be what makes this thing really powerful and handy. So ideally I would expect a radio button, forcing the user to choose between bidding and buying.

**Comment by Mardaneus86** [comment]
Yes, as I've stated in my previous comment, this is based on Buy Now only for now.

> - Based on Buy Now price only (otherwise we have to keep track of trade status and implement bidding logic. This is doable but way more complex.)

About the rare players: being rare is not an issue, but the variants of Specials might be useful to search for. For example: a player can have many special forms like IF (multiple), OTW, Halloween, etc...

**Comment by Qeekly** [comment]
When will this be realized and is there any chance of getting a ban from EA for using JS scripts?

**Comment by Mardaneus86** [comment]
@Qeekly: Of course there is always a chance of getting banned by EA by using any tool that helps you trade. I think it's stated in their ToS. Probably I should mention in the readme that the use of these scripts is are at the users own risk.

I am still testing this locally, it works great if used for short amounts of time. I need to fix the rate limiting before I want to push this to the public in order to prevent bans.

**Comment by Qeekly** [comment]
Check the change that I proposed for one of your scripts.
I think this is not a bad decision. Tell me how to change the script so that I get the price twice (or better in one) when I click the button, and not three, as now. That is, the problem is this: I click on the button and the price is received, then after a time there are two more price updates. How to fix it? I'm strong in php, java, but not strong at js.

**Comment by Qeekly** [comment]
For myself, I rewrote a bit of code for my style and added a few useful features that I need. This is an addition to the previous comment with the question.

```
(function () {
  'use strict';

	$(document).bind('DOMNodeInserted', function(event) {
		
		var playerImageUrl;
		var playerId
		
		if($(event.target).hasClass('DetailPanel')) {
			
			if($(event.target).find('#getMinBuyNowPrice').length === 0) {
				
				$(event.target).find('.bidOptions').append('<button id="getMinBuyNowPrice" class="list"><span class="btn-text">Buy Now (min.)</span><span class="btn-subtext coins" id="minBuyNow">Get Price</span></button>');
				$(event.target).find('.QuickListPanel').append('<button id="getMinBuyNowPrice" class="list"><span class="btn-text">Buy Now (min.)</span><span class="btn-subtext coins" id="minBuyNow">Get Price</span></button>');
				
			}
			
			$('.listFUTItem').click(function () {
				
				$('#minBuyNow').text('Get Price');
				
			});
			
			$('#getMinBuyNowPrice').click(function () {
				
				if($('body').find('.squadSlot').length === 0) {
				
					playerImageUrl = $('.listFUTItem.selected').find('.photo').attr('src');
					
				} else {
					
					playerImageUrl = $('.squadSlot.ui-slot-selected').find('.photo').attr('src');
				
				}
				
				playerId = playerImageUrl.substr(playerImageUrl.lastIndexOf('/') + 1).replace('.png', '');
				search(playerId, 9999999999).observe(this, handleSearch);
					
			});
			
		}
		
	});
	
	var minimumBIN = 9999999999;
	var maskedDefId = 0;
	var handleSearch = function handleSearch(t, data) {
		
		if(data.items.length > 0) {
			
			var newMinimumBIN = Math.min.apply(Math, data.items.map(function (o) { return o._auction.buyNowPrice; }));
			
			if(newMinimumBIN < minimumBIN) {
				
				minimumBIN = newMinimumBIN;
				$('#minBuyNow').text(minimumBIN);
			
				var random_time = Math.random()*(17000 - 8000 + 1) + 8000;
				setTimeout(function () { search(maskedDefId, minimumBIN).observe(this, handleSearch); }, random_time);
			
			} else {
			
				var lowestBIN = Math.min.apply(Math, data.items.map(function (o) { return o._auction.buyNowPrice; }));
				var player = repositories.Item.getStaticDataByDefId(maskedDefId);
			
				$('#minBuyNow').text(lowestBIN);
		  
		  }
		
		} else {
			
			var lowestBIN = Math.min.apply(Math, data.items.map(function (o) { return o._auction.buyNowPrice; }));
			var player = repositories.Item.getStaticDataByDefId(maskedDefId);
			$('#minBuyNow').text(lowestBIN);
		}
	
	};

	var search = function search(playerId, maxBuy) {
	
		minimumBIN = maxBuy;
		maskedDefId = playerId;
		
		if(maxBuy === 9999999999) {
			
			maxBuy = 0;
		
		}

		var searchCriteria = new transferobjects.SearchCriteria();
		searchCriteria.type = enums.SearchType.PLAYER;
		searchCriteria.defId = [maskedDefId];
		searchCriteria.maxBuy = maxBuy;

		return repositories.TransferMarket.search(searchCriteria);
	
	};

})();
```

**Comment by Mardaneus86** [comment]
@Qeekly: Please do not pollute issues with unrelated comments. Create a new issue and move the above comments to that issue for a new discussion.

**Comment by grzzywa** [comment]
@Mardaneus86 Can you paste a code how you created a new item (autobuyer) in nav#footer?

**Comment by Mardaneus86** [comment]
I will post an article on the wiki this evening to show how you can do that.

**Comment by Mardaneus86** [comment]
Keep in mind that the auto buyer is still in a highly experimental state and might cause some issues. It's also not very customisable yet.
