### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by anzhehong** [Mardaneus86/futwebapp-tampermonkey#89]
Hi, thanks so much for your helper tool.
BTW, I think maybe a new function called auto-buy-low could be added. If you are interested in letting me join you, please contact me!

**Comment by Mardaneus86** [comment]
That’s essentially the same as the autobuyer proof of concept (still viewable in a separate branch).

Autobuying is not something I want to provide with these addons because the general community frowns upon it.

If you want to help in any way, feel free to browse the issue list and do a Pull Request. Any help is appreciated!

In case you meant something different, feel free to reopen the issue and clarify.
