### ISSUE TITLE
List by Futbin price

### ISSUE THREAD

**Issue by Bendecks** [Mardaneus86/futwebapp-tampermonkey#91]
### Expected behavior:
Sort items in club by Futbin price

**Comment by Mardaneus86** [comment]
That's gonna be a tough one. Say you have 1000 players in your club, that would mean we need to send all these players to Futbin to get prices which would take some time.

We would also need to cache every player you have, because the same applies for getting all players by paging in the club.

I get why you want this, I've also thought about it before. But I don't know if there is a good approach to this. Feel free to discuss in this issue.

**Comment by cstlira** [comment]
What if we could export the player list + futbin price to an spreadsheet?

**Comment by Mardaneus86** [comment]
Futbin already provides this themselves. Not sure if we need a copy of similar functionality here.

We could store the complete club player list in Tampermonkey, but once in a while this list has to refreshed to remove the sold players and include the new ones. Hence looping the complete club again (this is how Futbin does it).

**Comment by cstlira** [comment]
FUTBIN doesn't have this feature anymore. They took down as EA could take actions against players account. :(

**Comment by Mardaneus86** [comment]
Is there any documentation to the exact reason? Perhaps looping through the club list a few times a day is a big red flag for EA?

**Comment by Kyderman** [comment]
EA said that browser extensions are against TOS.

As FUTBIN is a company they had to remove it, but in this case I think
you'll still be alright.

**Comment by Mardaneus86** [comment]
I doubt that's the case, because Futbin is scraping those player prices through the same plugin... Or am I missing something?

**Comment by Kyderman** [comment]
Yeah you are ;)

They are using it internally, so nobody actually "knows" they are.

**Comment by Mardaneus86** [comment]
Sorting based on Futbin price isn't supported by the web app API's. Suggestion is to download the club list, and proceed from there.

Cleaning up the issue list for the FIFA 19 update.
